@startuml
'https://plantuml.com/class-diagram

struct Subject {
+ name : string
+ marks : int[]
}

struct Student {
+ first_name : string
+ last_name : string
+ subjects : Subject[]
+ Init(last_name : string, first_name : string) : void
}

Subject *-- Student

struct StudentsDb {
+ PATH : string
+ id : int
+ students : map<int, Student>

+ Init() : void
+ Export() : void

+ Add(student : Student) : void
+ Update(student : Student) : void
+ Delete(id : int) : void

+ ToVector() : Student[]
}
Student *-- StudentsDb
@enduml